config/routes.rb
Rails.application.routes.draw do
  get    'tasks',          to: 'tasks#index'
  get    'tasks/new',      to: 'tasks#new'
  get    'tasks/:id',      to: 'tasks#show', as: 'task'
  post   'tasks',          to: 'tasks#create'
  get    'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch  'tasks/:id',   to: 'tasks#update'
  delete 'tasks/:id',      to: 'tasks#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:edit, :update, :show, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save!
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :details %>
  <%= form.text_field :details %>

  <%= form.label :completed %>
  <%= form.check_box  :completed %>

  <%= form.submit 'Save task' %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
  <ul>
   <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task) %>
      | <%= link_to 'Delete', destroy_path(task), method: :delete, class: "fa-trash-o" %></li>
    <% end %>
  </ul>
  <p><%= link_to 'Add new', tasks_new_path %></p>

app/views/tasks/new.html.erb
<%= form_for(@task) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :details %>
  <%= form.text_field :details %>

  <%= form.label :completed %>
  <%= form.check_box :completed %>

  <%= form.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
   <% link_to 'Delete', task_path(@task), method: :delete, class: "icon-trash" %>

    <p>Title:<%= @task.title %></p>

    <p>Details:<%= @task.details %></p>

    <p>Completed:<%= @task.completed %></p>

    <p><%= link_to 'Back to list', tasks_new_path %></p>

    <p><%= link_to 'Edit task', edit_path %></p>